// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';
// from the device language

class mylocale implements Translations {
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "Language": "اللغة",
          "home": "الصفحة الرئيسية",
          "Services": "الخدمات",
          "personal Page": "الصفحة الشخصية",
          "Select Image": "اختر الصورة",
          'mode': 'الوضع',
          "About": "الخصائص",
          "Love Your Soul": "اعتني بنفسك",
          "we pour love and care in every patient":
              "نحن نبذل الجهد والرعاية لكل المرضي ",
          "we make you never lose hope": "لن نجعلك تفقد الامل ابدا",
          "Top Ordered ": "الاعلي ترتيبا",
          " patient every day ": "عدد المرضي اليومي ",
          " Experience Nurses ": " الممرضين الخبراء ",
          " Patient Capacity ": " عدد المرضي الكلي  ",
          " Years Experience ": "سنوات الخبرة ",
          "Our job is to make you comfortable and save your life":
              "مهمتنا ان نجعلك مرتاحا والحفاظ علي حياتك ",
          "Pediatric Nursing": " رعاية الأطفال",
          "Elderly Nursing": " رعاية المسنين",
          "Special Care": "رعاية خاصة",
          "Emergency Nursing": "    تمريض الطوارئ",
          "Woman Nursing": "رعاية السيدات ",
          "Psychiatric Nursing": "الرعاية النفسية",
          "show more": "عرض المزيد",
          "order": "طلب",
          "All": "الكل ",
          "Male": "الرجال",
          "Female": "النساء",
          "Location": "الموقع",
          "Price": "السعر",
          "Active": "النشطاء",
          'Country': 'الدولة',
          'My profile ': 'حسابي الشخصي ',
          "English": "الانجليزية",
          "Arabic": "العربية",
          'Privacy policy': 'خصوصية الامان',
          'Dark mode': 'الوضع الداكن',
          'Settings': "الاعدادات",
          "Price : ": "السعر : ",
          "Rate : ": "التقييم : ",
          "Location : ": "الموقع : ",
          "Sign in": "تسجيل الدخول ",
          "Nursing , Care , Help": "التمريض ، الرعاية ، المساعدة",
          "Enter Your Email ": "ادخل بريدك الالكتروني",
          "Enter Your name": "ادخل اسمك ",
          "Enter Your Password": "ادخل كلمة السر",
          'Forget Password?': " نسيت كلمة السر ؟",
          "LOGIN": "تسجيل الدخول",
          "Do you have any accout?": "لديك حساب بالفعل ؟",
          "Don\'t have any accout?": "ليس لديك حساب ؟",
          "Sign Up": "انشاء حساب",
          "Enter New Password": "ادخل كلمة السر الجديدة",
          "Re Enter New Password": "اعد ادخال كلمة السر الجديدة",
          "Please Enter a New Password": "من فضلك ادخل كلمة السر الجديدة",
          "New Password ": "كلمة سر جديدة",
          "Reset Password": "تعيين كلمة سر حديدة ",
          "save Data": 'حفظ    ',
          "select  your Location": 'ادخل موقعك',
          "Your Education": "ادخل المرحلة التعليمية ",
          'Your Phone Number': 'ادخل رقم هاتفك',
          'Your Second Number (optional)': 'ادخل رقم هاتف اخر (اختياري)',
          'Write about your skills and Experience':
              'اكتب نبذة عن مهاراتك وخبراتك',
          "Choose Your Gender": "ادخل نوع جنسك",
          'Male': 'ذكر',
          // ignore: equal_keys_in_map
          'Female': 'انثي',
          'Your Birthday': 'ادخل تاريخ ميلادك ',
          "The Servant Price :": " سعر الخدمة :",
          "Your Full name": "ادخل اسمك",
          "Location :": "الموقع :",
          "Price :": "السعر :",
          "Rate :": "التقييم",

          "27": "فحص البريد الالكتروني",
          "28": "تم انشاء الحساب بنجاح",
          "29": "الرجاء ادخال البريد لتلقي رمز التحقق",
          "30": "فحص",
          "31": "الذهاب لتسجيل الدخول",
          "32": "نجاح",
          "33": "حفظ",
          "34": "الرجاء ادخال كلمة المرور الجديدة",
          "35": "الكلمة الجديدة",
          "36": "تم اعادة تعيين كلمة المرور بنجاح",
          "37": "تهانينا",
          "38": "تم التسجيل بنجاح"
        },
        "en": {
          "Language": "Language",
          "home": "home",
          "Select Image": "Select Image",
          "Services": "Services",
          "personal Page": "personal Page",
          "About": "About",
          "Love Your Soul": "Love Your Soul",
          "we pour love and care in every patient":
              "we pour love and care in every patient.",
          "we make you never lose hope": "we make you never lose hope",
          "Top Ordered ": "Top Ordered ",
          " patient every day ": " patient every day",
          " Experience Nurses ": " Experience Nurses ",
          " Patient Capacity ": " Patient Capacity ",
          " Years Experience ": " Years Experience ",
          "Our job is to make you comfortable and save your life":
              "Our job is to make you comfortable and save your life",
          "Pediatric Nursing": "Pediatric Nursing",
          "Elderly Nursing": "Elderly Nursing",
          "Special Care": "Special Care",
          "Emergency Nursing": "Emergency Nursing",
          "Woman Nursing": "Woman Nursing",
          "Psychiatric Nursing": "Psychiatric Nursing",
          "All": "All",
          "Male": "Male",
          "Female": "Female",
          "Location": "Location",
          "Price": "Price",
          "Active": "Active",
          'Settings': 'Settings',
          'Country': 'Country',
          'My profile ': 'My profile ',
          "English": "English",
          "Arabic": "Arabic",
          'Privacy policy': 'Privacy policy',
          'Dark mode': 'Dark mode',
          'Settings': 'Settings',
          "show more": "show more",
          "order": "order",
          "Price : ": "Price : ",
          "Rate : ": "Rate : ",
          "Location : ": "Location : ",
          "Sign In": "Sign In",
          "Nursing , Care , Help": "Nursing , Care , Help",
          "Enter Your Email ": "Enter Your Email ",
          "Enter Your Password": "Enter Your Password",
          'Forget Password?': 'Forget Password?',
          "LOGIN": "LOGIN",
          "Do you have any accout?": "Do you have any accout?",
          "Don\'t have any accout?": "Don\'t have any accout?",
          "Sign in": "Sign In",
          "Enter New Password": "Enter New Password",
          "Re Enter New Password": "Re Enter New Password",
          "Enter Your name": "Enter Your name",
          "Please Enter a New Password": "Please Enter a New Password",
          "New Password ": "New Password ",
          "Reset Password": "Reset Password",
          'Save': 'Save',
          "Your Full name": "Your Full name",
          "select  your Location": 'select Your Location',
          "Your Education": "Your Education",
          'Your Phone Number': 'Your Phone Number',
          'Your Second Number (optional)': 'Your Second Number (optional)',
          'Write about your skills and Experience':
              'Write about your skills and Experience',
          "Choose Your Gender": "Choose Your Gender",
          'Male': 'Male',
          'Female': 'Female',
          'Your Birthday': 'Your Birthday',
          " The Servant Price :": " The Servant Price :",
          "save Data": "save Data  ",
          "Location :": "Location :",
          "Price :": "Price :",
          "Rate :": "Rate :",
          'mode': 'mode',
          "12": "Enter Your Email",
          "13": "Enter Your Password",
          "14": "Forget Password",
          "15": "Sign In",
          "16": "Dont Have An Account ? ",
          "17": "Sign Up",
          "18": "Email",
          "19": "Password",
          "20": "Username",
          "21": "Phone",
          "22": "Enter Your Phone",
          "23": "Enter Your Username",
          "24":
              "Sign Up With Your Email And Password OR Continue With Social Media",
          "25": " have an account ? ",
          "26": "SignIn",
          "27": "Check Email",
          "28": "Account successfully created",
          "29": "please Enter Your Email Address To Recive A verification code",
          "30": "check",
          "31": "Go To Login",
          "32": "Success",
          "33": "save",
          "34": "Please Enter new Password",
          "35": "New Password",
          "36": "Password has been reset successfully",
          "37": "congratulations",
          "38": "successfully registered"
        }
      };
}
